In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("C:\\Users\\suhay\\Downloads\\matches.csv", index_col = 0)

In [38]:
data

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
0,2020-09-21,20:15,Premier League,Matchweek 2,Mon,Away,W,3,1,Wolves,...,2.0,1.0,1.0,2023,Manchester City,0,24,20,0,1
2,2020-09-27,16:30,Premier League,Matchweek 3,Sun,Home,L,2,5,Leicester City,...,1.0,0.0,0.0,2023,Manchester City,1,12,16,6,0
4,2020-10-03,17:30,Premier League,Matchweek 4,Sat,Away,D,1,1,Leeds United,...,1.0,0.0,0.0,2023,Manchester City,0,11,17,5,0
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,...,0.0,0.0,0.0,2023,Manchester City,1,0,17,5,1
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,...,1.0,0.0,0.0,2023,Manchester City,0,23,12,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2019-04-13,12:30,Premier League,Matchweek 34,Sat,Away,L,0,4,Tottenham,...,1.0,0.0,0.0,2021,Huddersfield Town,0,20,12,5,0
36,2019-04-20,15:00,Premier League,Matchweek 35,Sat,Home,L,1,2,Watford,...,1.0,0.0,0.0,2021,Huddersfield Town,1,21,15,5,0
37,2019-04-26,20:00,Premier League,Matchweek 36,Fri,Away,L,0,5,Liverpool,...,0.0,0.0,0.0,2021,Huddersfield Town,0,13,20,4,0
38,2019-05-05,14:00,Premier League,Matchweek 37,Sun,Home,D,1,1,Manchester Utd,...,1.0,0.0,0.0,2021,Huddersfield Town,1,15,14,6,0
39,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,D,1,1,Southampton,...,0.0,0.0,0.0,2021,Huddersfield Town,0,19,15,6,0

In [4]:
data.shape

(2280, 27)

In [5]:
38 * 20 * 3

2280

In [6]:
data['team'].value_counts()

Manchester City             114
Everton                     114
Burnley                     114
Brighton and Hove Albion    114
Southampton                 114
Crystal Palace              114
Manchester United           114
Newcastle United            114
Wolverhampton Wanderers     114
Arsenal                     114
Tottenham Hotspur           114
West Ham United             114
Leicester City              114
Chelsea                     114
Liverpool                   114
Aston Villa                  76
Fulham                       76
Sheffield United             76
Bournemouth                  76
Watford                      76
Leeds United                 38
West Bromwich Albion         38
Norwich City                 38
Cardiff City                 38
Huddersfield Town            38
Name: team, dtype: int64

In [7]:
data['round'].value_counts()

Matchweek 2     60
Matchweek 33    60
Matchweek 23    60
Matchweek 24    60
Matchweek 16    60
Matchweek 25    60
Matchweek 26    60
Matchweek 29    60
Matchweek 27    60
Matchweek 28    60
Matchweek 3     60
Matchweek 30    60
Matchweek 31    60
Matchweek 32    60
Matchweek 34    60
Matchweek 35    60
Matchweek 36    60
Matchweek 37    60
Matchweek 22    60
Matchweek 21    60
Matchweek 20    60
Matchweek 1     60
Matchweek 4     60
Matchweek 5     60
Matchweek 6     60
Matchweek 7     60
Matchweek 8     60
Matchweek 9     60
Matchweek 10    60
Matchweek 11    60
Matchweek 12    60
Matchweek 13    60
Matchweek 14    60
Matchweek 15    60
Matchweek 17    60
Matchweek 18    60
Matchweek 19    60
Matchweek 38    60
Name: round, dtype: int64

In [8]:
data.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [9]:
data['date'] = pd.to_datetime(data['date'])

In [10]:
data['venue_code'] = data['venue'].astype('category').cat.codes

In [11]:
data['opp_code'] = data['opponent'].astype('category').cat.codes

In [12]:
data['hour'] = data['time'].str.replace(":.+", "", regex=True).astype('int')

In [13]:
data['day_code'] = data['date'].dt.dayofweek

In [14]:
data['target'] = (data['result'] == 'W').astype('int')

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split = 10, random_state=1)

In [25]:
train = data[data['date']<'2021-01-01']

In [26]:
test = data[data['date'] > '2021-01-01']

In [27]:
predictors = ['venue_code', 'opp_code', 'hour', 'day_code']

In [28]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [29]:
preds = rf.predict(test[predictors])

In [30]:
from sklearn.metrics import accuracy_score

In [31]:
acc = accuracy_score(test['target'], preds)

In [32]:
acc

0.5336322869955157

In [33]:
combined = pd.DataFrame(dict(actual=test['target'], prediction = preds))

In [34]:
pd.crosstab(index=combined['actual'], columns = combined['prediction'])

prediction    0   1
actual
0           181  86
1           122  57

In [36]:
from sklearn.metrics import precision_score

In [37]:
precision_score(test['target'], preds)

0.3986013986013986

In [40]:
grouped_matches = data.groupby('team')

In [41]:
group = grouped_matches.get_group('Arsenal')

In [42]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2020-09-12,12:30,Premier League,Matchweek 1,Sat,Away,W,3,0,Fulham,...,2.0,0.0,0.0,2023,Arsenal,0,9,12,5,1
2,2020-09-19,20:00,Premier League,Matchweek 2,Sat,Home,W,2,1,West Ham,...,0.0,0.0,0.0,2023,Arsenal,1,23,20,5,1
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Away,L,1,3,Liverpool,...,0.0,0.0,0.0,2023,Arsenal,0,13,20,0,0
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,0.0,0.0,0.0,2023,Arsenal,1,18,14,6,1
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,2.0,0.0,0.0,2023,Arsenal,0,14,17,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2019-04-21,16:00,Premier League,Matchweek 35,Sun,Home,L,2,3,Crystal Palace,...,0.0,0.0,0.0,2021,Arsenal,1,7,16,6,0
51,2019-04-24,19:45,Premier League,Matchweek 31,Wed,Away,L,1,3,Wolves,...,1.0,0.0,0.0,2021,Arsenal,0,24,19,2,0
52,2019-04-28,12:00,Premier League,Matchweek 36,Sun,Away,L,0,3,Leicester City,...,0.0,0.0,0.0,2021,Arsenal,0,12,12,6,0
54,2019-05-05,16:30,Premier League,Matchweek 37,Sun,Home,D,1,1,Brighton,...,2.0,1.0,1.0,2021,Arsenal,1,3,16,6,0
56,2019-05-12,15:00,Premier League,Matchweek 38,Sun,Away,W,3,1,Burnley,...,0.0,0.0,0.0,2021,Arsenal,0,4,15,6,1

In [48]:
def rolling_averages(group, cols, new_cols): 
    group = group.sort_values('date')
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [49]:
cols = ['gf', 'ga', 'sh', 'sot', 'dist', 'fk', 'pk', 'pkatt']
new_cols = [f"{c}_rolling" for c in cols]

In [50]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [51]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2018-09-02,13:30,Premier League,Matchweek 4,Sun,Away,W,3,2,Cardiff City,...,6,1,1.666667,2.000000,13.666667,6.333333,18.166667,0.333333,0.0,0.0
4,2018-09-15,15:00,Premier League,Matchweek 5,Sat,Away,W,2,1,Newcastle Utd,...,5,1,2.666667,2.000000,16.333333,9.000000,17.300000,0.333333,0.0,0.0
6,2018-09-23,16:00,Premier League,Matchweek 6,Sun,Home,W,2,0,Everton,...,6,1,2.666667,1.333333,15.333333,7.666667,17.333333,0.666667,0.0,0.0
8,2018-09-29,15:00,Premier League,Matchweek 7,Sat,Home,W,2,0,Watford,...,5,1,2.333333,1.000000,12.666667,6.000000,17.133333,0.333333,0.0,0.0
10,2018-10-07,12:00,Premier League,Matchweek 8,Sun,Away,W,5,1,Fulham,...,6,1,2.000000,0.333333,10.000000,3.000000,16.666667,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2021-05-02,14:00,Premier League,Matchweek 34,Sun,Away,W,2,0,Newcastle Utd,...,6,1,1.333333,0.666667,15.333333,4.333333,17.533333,0.666667,0.0,0.0
54,2021-05-09,19:00,Premier League,Matchweek 35,Sun,Home,W,3,1,West Brom,...,6,1,1.000000,0.666667,17.000000,4.000000,17.100000,0.666667,0.0,0.0
55,2021-05-12,20:15,Premier League,Matchweek 36,Wed,Away,W,1,0,Chelsea,...,2,1,1.666667,0.666667,16.000000,4.666667,18.333333,0.666667,0.0,0.0
56,2021-05-19,19:00,Premier League,Matchweek 37,Wed,Away,W,3,1,Crystal Palace,...,2,1,2.000000,0.333333,13.000000,4.333333,19.133333,0.666667,0.0,0.0
57,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2,0,Brighton,...,6,1,2.333333,0.666667,8.666667,4.000000,18.200000,0.333333,0.0,0.0

In [53]:
matches_rolling = data.groupby('team').apply(lambda x: rolling_averages(x, cols, new_cols))

In [54]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 3  2018-09-02  13:30  Premier League   Matchweek 4
                        4  2018-09-15  15:00  Premier League   Matchweek 5
                        6  2018-09-23  16:00  Premier League   Matchweek 6
                        8  2018-09-29  15:00  Premier League   Matchweek 7
                        10 2018-10-07  12:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 37 2021-05-03  18:00  Premier League  Matchweek 34
                        38 2021-05-09  12:00  Premier League  Matchweek 35
                        39 2021-05-16  14:05  Premier League  Matchweek 36
                        40 2021-05-19  18:00  Premier League  Matchweek 37
                        41 2021-05-23  16:00  Premier League  Matchweek 38

                            day venue result  gf  ga        opponent  ...  \
team                                                                  ...
Arsenal                 3   Sun  Away      W   3   2    Cardiff City  ...
                        4   Sat  Away      W   2   1   Newcastle Utd  ...
                        6   Sun  Home      W   2   0         Everton  ...
                        8   Sat  Home      W   2   0         Watford  ...
                        10  Sun  Away      W   5   1          Fulham  ...
...                         ...   ...    ...  ..  ..             ...  ...
Wolverhampton Wanderers 37  Mon  Away      D   1   1       West Brom  ...
                        38  Sun  Home      W   2   1        Brighton  ...
                        39  Sun  Away      L   0   2       Tottenham  ...
                        40  Wed  Away      L   0   1         Everton  ...
                        41  Sun  Home      L   1   2  Manchester Utd  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 3          6       1    1.666667    2.000000
                        4          5       1    2.666667    2.000000
                        6          6       1    2.666667    1.333333
                        8          5       1    2.333333    1.000000
                        10         6       1    2.000000    0.333333
...                              ...     ...         ...         ...
Wolverhampton Wanderers 37         0       0    0.666667    1.333333
                        38         6       1    0.666667    1.666667
                        39         6       0    1.000000    2.000000
                        40         2       0    1.000000    1.333333
                        41         6       0    0.666667    1.333333

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 3   13.666667    6.333333    18.166667   0.333333
                        4   16.333333    9.000000    17.300000   0.333333
                        6   15.333333    7.666667    17.333333   0.666667
                        8   12.666667    6.000000    17.133333   0.333333
                        10  10.000000    3.000000    16.666667   0.333333
...                               ...         ...          ...        ...
Wolverhampton Wanderers 37   9.666667    3.000000    17.766667   0.666667
                        38  14.000000    5.333333    19.133333   0.333333
                        39  16.000000    6.000000    21.433333   0.666667
                        40  17.000000    6.333333    19.033333   0.333333
                        41  13.333333    4.000000    19.866667   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 3          0.0            0.0
                        4          0.0            0.0
                        6          0.0            0.0
                        8          0.0            0.0
                        10         0.0            0.0
...                                ...            ...
Wolverhampton Wanderers 37         0.0            0.0
                        38         0.0            0.0
                        39         0.0            0.0
                        40         0.0            0.0
                        41         0.0            0.0

[2199 rows x 40 columns]

In [55]:
matches_rolling = matches_rolling.droplevel('team')

In [56]:
matches_rolling.index = range(matches_rolling.shape[0])

In [58]:
def make_predictions(data, predictors):
    train = data[data['date']<'2021-01-01']
    test = data[data['date'] > '2021-01-01'] 
    rf.fit(train[predictors], train['target'])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test['target'], prediction = preds))
    precision = precision_score(test['target'], preds)
    return combined, precision

In [59]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [60]:
precision

0.5376344086021505

In [61]:
combined

      actual  prediction
89         1           0
90         0           1
91         1           1
92         1           1
93         0           0
...      ...         ...
2194       0           0
2195       1           0
2196       0           0
2197       0           0
2198       0           0

[446 rows x 2 columns]

In [63]:
combined = combined.merge(matches_rolling[['date', 'team', 'opponent']], left_index = True, right_index = True)

In [67]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
    
map_values = {
    'Brighton and Hove Albion': 'Brighton',
    'Manchester United': 'Manchester Utd',
    'Newcastle United': 'Newcastle Utd',
    'Tottenham Hotspur': 'Tottenham',
    'West Ham United' : 'West Ham',
    'Wolverhampton Wanderers': 'Wolves'
    
}
mapping = MissingDict(**map_values)

In [68]:
combined['new_team'] = combined['team'].map(mapping)

In [69]:
merged = combined.merge(combined, left_on=['date', 'new_team'], right_on = ['date', 'opponent'])

In [70]:
merged

,actual_x,prediction_x,date,team_x,opponent_x,new_team_x,actual_y,prediction_y,team_y,opponent_y,new_team_y
0,1,0,2021-01-02,Arsenal,West Brom,Arsenal,0,0,West Bromwich Albion,Arsenal,West Bromwich Albion
1,0,1,2021-01-14,Arsenal,Crystal Palace,Arsenal,0,0,Crystal Palace,Arsenal,Crystal Palace
2,1,1,2021-01-18,Arsenal,Newcastle Utd,Arsenal,0,0,Newcastle United,Arsenal,Newcastle Utd
3,1,1,2021-01-26,Arsenal,Southampton,Arsenal,0,0,Southampton,Arsenal,Southampton
4,0,0,2021-01-30,Arsenal,Manchester Utd,Arsenal,0,0,Manchester United,Arsenal,Manchester Utd
...,...,...,...,...,...,...,...,...,...,...,...
397,0,0,2021-05-03,Wolverhampton Wanderers,West Brom,Wolves,0,0,West Bromwich Albion,Wolves,West Bromwich Albion
398,1,0,2021-05-09,Wolverhampton Wanderers,Brighton,Wolves,0,0,Brighton and Hove Albion,Wolves,Brighton
399,0,0,2021-05-16,Wolverhampton Wanderers,Tottenham,Wolves,1,1,Tottenham Hotspur,Wolves,Tottenham
400,0,0,2021-05-19,Wolverhampton Wanderers,Everton,Wolves,1,1,Everton,Wolves,Everton
401,0,0,2021-05-23,Wolverhampton Wanderers,Manchester Utd,Wolves,1,0,Manchester United,Wolves,Manchester Utd

In [74]:
merged[(merged['prediction_x'] == 1) & (merged['prediction_y'] == 0)]['actual_x'].value_counts()

1    46
0    42
Name: actual_x, dtype: int64

In [75]:
46/40

1.15

In [76]:
46/88

0.5227272727272727